### ISSUE TITLE
Server Issue

### ISSUE THREAD

**Issue by uk-twistic2** [Iskallia/Vault-public-S1#115]
```
[09:44:56] [Server thread/INFO] [minecraft/DedicatedServer]: MCSList has created a Omega Vault!
[09:46:50] [Server thread/INFO] [STDERR/]: [iskallia.vault.world.data.VaultRaidData:lambda$startNew$5:122]: java.lang.NullPointerException
[09:46:50] [Server thread/INFO] [STDERR/]: [iskallia.vault.world.data.VaultRaidData:lambda$startNew$5:122]:     at iskallia.vault.world.data.VaultRaidData.lambda$startNew$5(VaultRaidData.java:106)
[09:46:50] [Server thread/INFO] [STDERR/]: [iskallia.vault.world.data.VaultRaidData:lambda$startNew$5:122]:     at net.minecraft.util.concurrent.ThreadTaskExecutor.func_222818_b(SourceFile:59)
[09:46:50] [Server thread/INFO] [STDERR/]: [iskallia.vault.world.data.VaultRaidData:lambda$startNew$5:122]:     at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
[09:46:50] [Server thread/INFO] [STDERR/]: [iskallia.vault.world.data.VaultRaidData:lambda$startNew$5:122]:     at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
[09:46:50] [Server thread/INFO] [STDERR/]: [iskallia.vault.world.data.VaultRaidData:lambda$startNew$5:122]:     at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
[09:46:50] [Server thread/INFO] [STDERR/]: [iskallia.vault.world.data.VaultRaidData:lambda$startNew$5:122]:     at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
[09:46:50] [Server thread/INFO] [STDERR/]: [iskallia.vault.world.data.VaultRaidData:lambda$startNew$5:122]:     at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:730)
[09:46:50] [Server thread/INFO] [STDERR/]: [iskallia.vault.world.data.VaultRaidData:lambda$startNew$5:122]:     at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:156)
[09:46:50] [Server thread/INFO] [STDERR/]: [iskallia.vault.world.data.VaultRaidData:lambda$startNew$5:122]:     at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
[09:46:50] [Server thread/INFO] [STDERR/]: [iskallia.vault.world.data.VaultRaidData:lambda$startNew$5:122]:     at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:713)
[09:46:50] [Server thread/INFO] [STDERR/]: [iskallia.vault.world.data.VaultRaidData:lambda$startNew$5:122]:     at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:707)
[09:46:50] [Server thread/INFO] [STDERR/]: [iskallia.vault.world.data.VaultRaidData:lambda$startNew$5:122]:     at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127)
[09:46:50] [Server thread/INFO] [STDERR/]: [iskallia.vault.world.data.VaultRaidData:lambda$startNew$5:122]:     at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:693)
[09:46:50] [Server thread/INFO] [STDERR/]: [iskallia.vault.world.data.VaultRaidData:lambda$startNew$5:122]:     at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
[09:46:50] [Server thread/INFO] [STDERR/]: [iskallia.vault.world.data.VaultRaidData:lambda$startNew$5:122]:     at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:229)
[09:46:50] [Server thread/INFO] [STDERR/]: [iskallia.vault.world.data.VaultRaidData:lambda$startNew$5:122]:     at java.lang.Thread.run(Unknown Source)

```
Can't load any Vaults nothing happens and when I run the command (/the_vault raid VAULT start) it gives this error
World Type: [Server]
The_Vault Version [e.g. 1.0.1]

**Comment by MVPlel** [comment]
Found a fix seemed to have been something to do with Ram issue added 10GB and worked fine.

If anyone wants a server pack because curse is to slow at posting I will provide a DL link

**Comment by hannah98** [comment]
@MVPlel - I'd be interested in a server pack if you as still able.  What is the difference between the client-side modpack and the server modpack?  (I found there *is* a difference because installing the pack from Discord on my server did not work).

**Comment by MVPlel** [comment]
Please NOTE this is NOT the official server pack so please use at your own will and this is what I have done for my self.
https://drive.google.com/file/d/17DB-0bUO-qcfzUAxg_08nTDO8iIbul-j/view?usp=sharing

NOTE not an official server either but if you wanted to join a server 
vaulthunter.eu0.co.uk > we are trying to make it fair to give you traders and items like you  would in the modpack but not making it to op. 

This pack for sure is one of the best that has been made in a while and must say a massive thank you to the team who have worked on this pack!

**Comment by hannah98** [comment]
@MVPlel Thank you so much for sharing! I sent a request on drive since I didn't have access.

And thank you for the server address - I may pop in and check it out!

**Comment by MVPlel** [comment]
No problem, I have accepted

**Comment by hannah98** [comment]
@MVPlel Got it - thank you so much!

**Comment by MVPlel** [comment]
No problem
