### ISSUE TITLE
crashing in menu

### ISSUE THREAD

**Issue by creeddevyl** [Iskallia/Vault-public-S1#240]
every i go into the menu by pressing L i click on immersive engenering it frezzes then crashes its the only tab that does it

**Comment by BONNe** [comment]
Could you share which modpack version do you use?

**Comment by creeddevyl** [comment]
the version is 1.2 zip officel mod pack thats what i got from the forge and a;so i forgot it keeps saying Xaeros mini n world maps need updates but there up yo date

**Comment by creeddevyl** [comment]
its still crashing on that tab it was gone then the tab came back so i put the crash log here --- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 4/29/21 8:31 PM
Description: Rendering item

java.lang.NullPointerException: Rendering item
	at blusunrize.immersiveengineering.common.items.BuzzsawItem.canBuzzsawBeUsed(BuzzsawItem.java:423) ~[?:?] {re:classloading}
	at blusunrize.immersiveengineering.common.items.BuzzsawItem.shouldRotate(BuzzsawItem.java:803) ~[?:?] {re:classloading}
	at blusunrize.immersiveengineering.common.items.BuzzsawItem.getTransformForGroups(BuzzsawItem.java:828) ~[?:?] {re:classloading}
	at blusunrize.immersiveengineering.client.render.IEOBJItemRenderer.func_239207_a_(IEOBJItemRenderer.java:82) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.ItemRenderer.func_229111_a_(ItemRenderer.java:137) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemRenderer.func_191962_a(ItemRenderer.java:236) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemRenderer.func_239387_b_(ItemRenderer.java:265) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemRenderer.func_239390_c_(ItemRenderer.java:253) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.advancements.AdvancementEntryGui.func_238688_a_(SourceFile:151) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.advancements.AdvancementEntryGui.func_238688_a_(SourceFile:155) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.advancements.AdvancementEntryGui.func_238688_a_(SourceFile:155) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.advancements.AdvancementEntryGui.func_238688_a_(SourceFile:155) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.advancements.AdvancementTabGui.func_238682_a_(AdvancementTabGui.java:118) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.advancements.AdvancementsScreen.func_238696_c_(AdvancementsScreen.java:132) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.advancements.AdvancementsScreen.func_230430_a_(AdvancementsScreen.java:102) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:299) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:492) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_gamerenderer_resetprojectionmatrix,xf:fml:xaerominimap:xaero_gamerenderer_renderworld,pl:mixin:APP:dungeons_gear.mixins.json:GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.13.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$482/1499588909.call(Unknown Source) [forge-1.16.5-36.1.13.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at blusunrize.immersiveengineering.common.items.BuzzsawItem.canBuzzsawBeUsed(BuzzsawItem.java:423) ~[?:?] {re:classloading}
	at blusunrize.immersiveengineering.common.items.BuzzsawItem.shouldRotate(BuzzsawItem.java:803) ~[?:?] {re:classloading}
	at blusunrize.immersiveengineering.common.items.BuzzsawItem.getTransformForGroups(BuzzsawItem.java:828) ~[?:?] {re:classloading}
	at blusunrize.immersiveengineering.client.render.IEOBJItemRenderer.func_239207_a_(IEOBJItemRenderer.java:82) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.ItemRenderer.func_229111_a_(ItemRenderer.java:137) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemRenderer.func_191962_a(ItemRenderer.java:236) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
-- Item being rendered --
Details:
	Item Type: buzzsaw
	Registry Name: immersiveengineering:buzzsaw
	Item Damage: 0
	Item NBT: {sawblade_spare1:{id:"immersiveengineering:sawblade",Count:1b,tag:{Damage:0}},sawblade_spare2:{id:"immersiveengineering:sawblade",Count:1b,tag:{Damage:0}},sawblade:{id:"immersiveengineering:sawblade",Count:1b,tag:{Damage:0}},upgrades:{spareblades:1b,oiled:1b}}
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.ItemRenderer.func_239387_b_(ItemRenderer.java:265) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemRenderer.func_239390_c_(ItemRenderer.java:253) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.advancements.AdvancementEntryGui.func_238688_a_(SourceFile:151) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.advancements.AdvancementEntryGui.func_238688_a_(SourceFile:155) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.advancements.AdvancementEntryGui.func_238688_a_(SourceFile:155) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.advancements.AdvancementEntryGui.func_238688_a_(SourceFile:155) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.advancements.AdvancementTabGui.func_238682_a_(AdvancementTabGui.java:118) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.advancements.AdvancementsScreen.func_238696_c_(AdvancementsScreen.java:132) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.advancements.AdvancementsScreen.func_230430_a_(AdvancementsScreen.java:102) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:299) ~[?:?] {re:classloading}


-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.advancements.AdvancementsScreen
	Mouse location: Scaled: (251, 46). Absolute: (1006.000000, 186.000000)
	Screen size: Scaled: (480, 255). Absolute: (1920, 1017). Scale factor of 4.000000

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['creeddevil1'/88, l='ClientLevel', x=-139.05, y=29.00, z=1428.30]]
	Chunk stats: Client Chunk Cache: 841, 574
	Level dimension: minecraft:overworld
	Level spawn location: World: (-48,63,-22), Chunk: (at 0,3,10 in -3,-2; contains blocks -48,0,-32 to -33,255,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 3205814 game time, 943077 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:classloading,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,xf:fml:xaerominimap:xaero_clientworldclass,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.13.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$482/1499588909.call(Unknown Source) [forge-1.16.5-36.1.13.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1769227504 bytes (1687 MB) / 6218055680 bytes (5930 MB) up to 7456948224 bytes (7111 MB)
	CPUs: 12
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8000m -Xms256m -XX:PermSize=256m
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.13.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.13.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.13.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.13.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.13.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.13
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		rsrequestify-1.16.3-2.0.1.jar                     |RSRequestify                  |rsrequestify                  |2.0.1               |DONE      |NOSIGNATURE
		mcw-windows-1.0.2-mc1.16.3.jar                    |Macaw's Windows               |mcwwindows                    |1.0.2               |DONE      |NOSIGNATURE
		rsgauges-1.16.3-1.2.5.jar                         |Gauges and Switches           |rsgauges                      |1.2.5               |DONE      |NOSIGNATURE
		IronJetpacks-1.16.3-4.1.2.jar                     |Iron Jetpacks                 |ironjetpacks                  |4.1.2               |DONE      |NOSIGNATURE
		XaerosWorldMap_1.13.4_Forge_1.16.5.jar            |Xaero's World Map             |xaeroworldmap                 |1.13.4              |DONE      |NOSIGNATURE
		CookingForBlockheads_1.16.3-9.2.2.jar             |Cooking for Blockheads        |cookingforblockheads          |9.2.2               |DONE      |NOSIGNATURE
		Controlling-7.0.0.9.jar                           |Controlling                   |controlling                   |7.0.0.9             |DONE      |NOSIGNATURE
		dankstorage-3.11.jar                              |Dank Storage                  |dankstorage                   |3.11                |DONE      |NOSIGNATURE
		Powah-1.16.3-2.3.4.jar                            |Powah                         |powah                         |2.3.4               |DONE      |NOSIGNATURE
		ftb-gui-library-1604.1.1.26.jar                   |FTB GUI Library               |ftbguilibrary                 |1604.1.1.26         |DONE      |NOSIGNATURE
		rangedpumps-0.8.2.jar                             |Ranged Pumps                  |rangedpumps                   |0.8.2               |DONE      |NOSIGNATURE
		branders-spawnermod-1.16.3-1.7.9.jar              |Enhanced Mob Spawners         |spawnermod                    |1.7.9               |DONE      |NOSIGNATURE
		Bookshelf-1.16.3-8.7.20.jar                       |Bookshelf                     |bookshelf                     |8.7.20              |DONE      |NOSIGNATURE
		u_team_core-1.16.3-3.1.12.185.jar                 |U Team Core                   |uteamcore                     |3.1.12.185          |DONE      |f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		buildinggadgets-3.7.2.jar                         |Building Gadgets              |buildinggadgets               |3.7.2               |DONE      |NOSIGNATURE
		mcw-doors-1.0.1fix-mc1.16.3-1.16.2.jar            |Macaw's Doors                 |mcwdoors                      |1.0.1               |DONE      |NOSIGNATURE
		Morpheus-1.16.3-4.2.63.jar                        |Morpheus                      |morpheus                      |4.2.63              |DONE      |NOSIGNATURE
		MekanismGenerators-1.16.4-10.0.17.444.jar         |Mekanism: Generators          |mekanismgenerators            |10.0.17             |DONE      |NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |DONE      |NOSIGNATURE
		JustEnoughResources-1.16.3-0.12.0.100.jar         |Just Enough Resources         |jeresources                   |0.12.0.100          |DONE      |NOSIGNATURE
		shetiphiancore-1.16-3.8.4.jar                     |ShetiPhian-Core               |shetiphiancore                |3.8.4               |DONE      |NOSIGNATURE
		refinedstorage-1.9.9.jar                          |Refined Storage               |refinedstorage                |1.9.9               |DONE      |NOSIGNATURE
		PrettyPipes-1.9.0.jar                             |Pretty Pipes                  |prettypipes                   |1.9.0               |DONE      |NOSIGNATURE
		corpse-1.16.3-1.0.6.jar                           |Corpse                        |corpse                        |1.16.3-1.0.6        |DONE      |NOSIGNATURE
		mcw-bridges-1.0.4-mc1.16.3.jar                    |Macaw's Bridges               |mcwbridges                    |1.0.4               |DONE      |NOSIGNATURE
		industrial-foregoing-1.16.4-3.2.7-7d95990.jar     |Industrial Foregoing          |industrialforegoing           |3.2.7               |DONE      |NOSIGNATURE
		torchmaster-2.3.4-alpha.jar                       |Torchmaster                   |torchmaster                   |2.3.4-alpha         |DONE      |NOSIGNATURE
		Compressium-1.16.4-1.1.36.jar                     |Compressium                   |compressium                   |1.1.36              |DONE      |NOSIGNATURE
		valkyrielib-1.16.3-3.0.3.2.jar                    |ValkyrieLib                   |valkyrielib                   |1.16.3-3.0.3.2      |DONE      |NOSIGNATURE
		Lollipop-1.16.3-3.2.2.jar                         |Lollipop                      |lollipop                      |3.2.2               |DONE      |NOSIGNATURE
		ironfurnaces-1.16.3-2.4.0.jar                     |Iron Furnaces                 |ironfurnaces                  |2.4.0               |DONE      |NOSIGNATURE
		masonry-1.16.3-0.3.6.jar                          |Masonry                       |masonry                       |NONE                |DONE      |NOSIGNATURE
		simplylight-1.16.4-1.1.1.jar                      |Simply Light                  |simplylight                   |1.16.4-1.1.1        |DONE      |NOSIGNATURE
		simplybackpacks-1.16.3-1.4.13.jar                 |Simply Backpacks              |simplybackpacks               |1.16.3-1.4.13       |DONE      |NOSIGNATURE
		curios-forge-1.16.4-4.0.3.0.jar                   |Curios API                    |curios                        |1.16.4-4.0.3.0      |DONE      |NOSIGNATURE
		Botania-1.16.3-409.jar                            |Botania                       |botania                       |1.16.3-409          |DONE      |NOSIGNATURE
		Patchouli-1.16.2-47.jar                           |Patchouli                     |patchouli                     |1.16.2-47           |DONE      |NOSIGNATURE
		camera-1.16.3-1.0.6.jar                           |Camera Mod                    |camera                        |1.16.3-1.0.6        |DONE      |NOSIGNATURE
		blockcarpentry-1.16-0.3.5a.jar                    |BlockCarpentry                |blockcarpentry                |1.16-0.3.5a         |DONE      |NOSIGNATURE
		elevatorid-1.16.3-1.7.6.jar                       |Elevator Mod                  |elevatorid                    |1.16.3-1.7.6        |DONE      |NOSIGNATURE
		neoncraft-2.1.jar                                 |Neon Craft                    |neoncraft                     |2.1                 |DONE      |NOSIGNATURE
		Runelic-1.16.3-5.0.1.jar                          |Runelic                       |runelic                       |5.0.1               |DONE      |NOSIGNATURE
		DarkUtilities-1.16.3-6.0.3.jar                    |Dark Utilities                |darkutils                     |6.0.3               |DONE      |NOSIGNATURE
		mcws-roofs-1.16.3-v2.0.0.jar                      |Macaw's Roofs                 |mcwroofs                      |2.0.0               |DONE      |NOSIGNATURE
		furniture-7.0.0-pre19-1.16.3.jar                  |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre19         |DONE      |NOSIGNATURE
		trashcans-1.0.6-mc1.16.3.jar                      |Trash Cans                    |trashcans                     |1.0.6               |DONE      |NOSIGNATURE
		dungeons_gear-1.16.4-3.0.6.jar                    |Dungeons Gear                 |dungeons_gear                 |3.0.6               |DONE      |NOSIGNATURE
		Cucumber-1.16.3-4.1.3.jar                         |Cucumber Library              |cucumber                      |4.1.3               |DONE      |NOSIGNATURE
		snad-1.0.2-1.16.3.jar                             |Snad                          |snad                          |1.0.2               |DONE      |NOSIGNATURE
		platforms-1.16-1.7.8.jar                          |Platforms                     |platforms                     |1.7.8               |DONE      |NOSIGNATURE
		jei-1.16.3-7.6.0.51.jar                           |Just Enough Items             |jei                           |7.6.0.50            |DONE      |NOSIGNATURE
		metalbarrels-3.3a.jar                             |Metal Barrels                 |metalbarrels                  |3.3a                |DONE      |NOSIGNATURE
		Mekanism-1.16.4-10.0.17.444.jar                   |Mekanism                      |mekanism                      |10.0.17             |DONE      |NOSIGNATURE
		invtweaks-1.16.2-1.0.0.jar                        |Inventory Tweaks Renewed      |invtweaks                     |1.16.2-1.0.0        |DONE      |NOSIGNATURE
		create-mc1.16.3+4_v0.3.jar                        |Create                        |create                        |mc1.16.3_v0.3+custom|DONE      |NOSIGNATURE
		Waystones_1.16.3-7.3.1.jar                        |Waystones                     |waystones                     |7.3.1               |DONE      |NOSIGNATURE
		enviromats-1.16.3-2.0.3.2.jar                     |Environmental Materials       |enviromats                    |1.16.3-2.0.3.2      |DONE      |NOSIGNATURE
		comforts-forge-1.16.3-4.0.0.1.jar                 |Comforts                      |comforts                      |1.16.3-4.0.0.1      |DONE      |NOSIGNATURE
		appliedenergistics2-8.1.0.jar                     |Applied Energistics 2         |appliedenergistics2           |8.1.0               |DONE      |95:58:cc:83:9d:a8:fa:4f:e9:f3:54:90:66:61:c8:ae:9c:08:88:11:52:52:df:2d:28:5f:05:d8:28:57:0f:98
		framedcompactdrawers-1.16-2.2.0.jar               |Framed Compacting Drawers     |framedcompactdrawers          |1.16-2.2.0          |DONE      |NOSIGNATURE
		DimStorage-1.16.5-4.4.0.jar                       |DimStorage                    |dimstorage                    |4.4.0               |DONE      |NOSIGNATURE
		decorative_blocks-1.16.4-1.7.0.jar                |Decorative Blocks             |decorative_blocks             |1.7.0               |DONE      |NOSIGNATURE
		mcjtylib-1.16-5.0.15.jar                          |McJtyLib                      |mcjtylib                      |1.16-5.0.15         |DONE      |NOSIGNATURE
		rftoolsbase-1.16-2.0.9.jar                        |RFToolsBase                   |rftoolsbase                   |1.16-2.0.9          |DONE      |NOSIGNATURE
		xnet-1.16-3.0.11.jar                              |XNet                          |xnet                          |1.16-3.0.11         |DONE      |NOSIGNATURE
		rftoolsstorage-1.16-2.0.8.jar                     |RFToolsStorage                |rftoolsstorage                |1.16-2.0.8          |DONE      |NOSIGNATURE
		restrictions-1.16-3.0.3.jar                       |Restrictions                  |restrictions                  |1.16-3.0.3          |DONE      |NOSIGNATURE
		JEITweaker-1.16.3-1.0.1.4.jar                     |JEI Tweaker                   |jeitweaker                    |1.0.1.4             |DONE      |NOSIGNATURE
		mininggadgets-1.7.0.jar                           |Mining Gadgets                |mininggadgets                 |1.7.0               |DONE      |NOSIGNATURE
		entitydetectors-1.16.3-1.1.0.0.jar                |Entity Detectors              |entitydetectors               |1.1.0.0             |DONE      |NOSIGNATURE
		CraftTweaker-1.16.3-7.0.0.48.jar                  |CraftTweaker                  |crafttweaker                  |7.0.0.48            |DONE      |NOSIGNATURE
		rftoolspower-1.16-3.0.8.jar                       |RFToolsPower                  |rftoolspower                  |1.16-3.0.8          |DONE      |NOSIGNATURE
		extradisks-1.16.4-1.3.4.jar                       |Extra Disks                   |extradisks                    |1.3.4               |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.13-universal.jar                |Forge                         |forge                         |36.1.13             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Waddles-1.16.4-0.8.11.jar                         |Waddles                       |waddles                       |1.16.4-0.8.11       |DONE      |NOSIGNATURE
		iskallutilities-1.2.jar                           |Iskall Utilities              |iskallutilities               |1.2                 |DONE      |NOSIGNATURE
		ironchest-1.16.4-11.2.10.jar                      |Iron Chests                   |ironchest                     |1.16.4-11.2.10      |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.13-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		cofh_core-1.16.3-1.1.6.jar                        |CoFH Core                     |cofh_core                     |1.1.6               |DONE      |NOSIGNATURE
		thermal_foundation-1.16.3-1.1.6.jar               |Thermal Series                |thermal                       |1.1.6               |DONE      |NOSIGNATURE
		thermal_innovation-1.16.3-1.1.7.jar               |Thermal Innovation            |thermal_innovation            |1.1.7               |DONE      |NOSIGNATURE
		thermal_expansion-1.16.3-1.1.6.jar                |Thermal Expansion             |thermal_expansion             |1.1.6               |DONE      |NOSIGNATURE
		thermal_locomotion-1.16.3-1.1.6.jar               |Thermal Locomotion            |thermal_locomotion            |1.1.6               |DONE      |NOSIGNATURE
		rftoolsutility-1.16-3.0.20.jar                    |RFToolsUtility                |rftoolsutility                |1.16-3.0.20         |DONE      |NOSIGNATURE
		MouseTweaks-2.13-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.13                |DONE      |NOSIGNATURE
		titanium-1.16.4-3.2.4.jar                         |Titanium                      |titanium                      |3.2.4               |DONE      |NOSIGNATURE
		ImmersiveEngineering-1.16.3-4.1.1-127.jar         |Immersive Engineering         |immersiveengineering          |1.16.3-4.1.1-127    |DONE      |44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		useful_railroads-1.16.3-1.4.6.33.jar              |Useful Railroads              |usefulrailroads               |1.4.6.33            |DONE      |f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		movingelevators-1.2.31a-mc1.16.3.jar              |Moving Elevators              |movingelevators               |1.2.31a             |DONE      |NOSIGNATURE
		storage_overhaul-1.16.3-1.0.3.jar                 |Storage Overhaul              |storage_overhaul              |1.16.3-1.0.3        |DONE      |NOSIGNATURE
		rftoolsbuilder-1.16-3.0.13.jar                    |RFToolsBuilder                |rftoolsbuilder                |1.16-3.0.13         |DONE      |NOSIGNATURE
		jeiintegration_1.16.3-6.0.0.8.jar                 |JEI Integration               |jeiintegration                |6.0.0.8             |DONE      |NOSIGNATURE
		easy_villagers-1.16.3-1.0.4.jar                   |Easy Villagers                |easy_villagers                |1.16.3-1.0.4        |DONE      |NOSIGNATURE
		Xaeros_Minimap_21.7.1_Forge_1.16.5.jar            |Xaero's Minimap               |xaerominimap                  |21.7.1              |DONE      |NOSIGNATURE
		ftb-backups-2.1.1.6.jar                           |FTB Backups                   |ftbbackups                    |2.1.1.6             |DONE      |NOSIGNATURE
		thermal_cultivation-1.16.3-1.1.6.jar              |Thermal Cultivation           |thermal_cultivation           |1.1.6               |DONE      |NOSIGNATURE
		AutoRegLib-1.6-47.jar                             |AutoRegLib                    |autoreglib                    |1.6-47              |DONE      |NOSIGNATURE
		Quark-r2.4-278.jar                                |Quark                         |quark                         |r2.4-278            |DONE      |NOSIGNATURE
		StorageDrawers-1.16.3-8.2.1.jar                   |Storage Drawers               |storagedrawers                |8.2.1               |DONE      |NOSIGNATURE
		FluxNetworks-1.16.4-6.1.5.10.jar                  |Flux Networks                 |fluxnetworks                  |1.16.4-6.1.5.10     |DONE      |NOSIGNATURE
		PickleTweaks-1.16.3-5.1.3.jar                     |Pickle Tweaks                 |pickletweaks                  |5.1.3               |DONE      |NOSIGNATURE
		AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |DONE      |NOSIGNATURE
		engineersdecor-1.16.3-1.1.4.jar                   |Engineer's Decor              |engineersdecor                |1.1.4               |DONE      |bf:30:76:97:e4:58:41:61:2a:f4:30:d3:8f:4c:e3:71:1d:14:c4:a1:4e:85:36:e3:1d:aa:2f:cb:22:b0:04:9b
		modular-routers-1.16.3-7.2.0-39.jar               |Modular Routers               |modularrouters                |1.16.3-7.2.0-39     |DONE      |NOSIGNATURE
		byg-1.1.5.jar                                     |Oh The Biomes You'll Go       |byg                           |1.1.5               |DONE      |NOSIGNATURE
		refinedstorageaddons-0.7.2.jar                    |Refined Storage Addons        |refinedstorageaddons          |0.7.2               |DONE      |NOSIGNATURE
		EnderMail-1.16.3-1.1.5.jar                        |Ender Mail                    |endermail                     |1.16.3-1.1.5        |DONE      |NOSIGNATURE
		the_vault-1.0.2-public.jar                        |The Vault                     |the_vault                     |1.0.2-public        |DONE      |NOSIGNATURE
	Crash Report UUID: 5091955f-0df4-42f0-8876-53f9a6604aa9
	Patchouli open book context: n/a
	Launched Version: forge-36.1.13
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 4.6.0 NVIDIA 465.89, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz

**Comment by BONNe** [comment]
Oh, it is very easy to explain why it crashes.

The pack is designed for Minecraft 1.16.3, not 1.16.5.

It is just not how it works, you cannot set it to 1.16.5 without updating every used mod and recompiling the Vault mod version to minecraft 1.16.5 version :)

**Comment by creeddevyl** [comment]
How do I go about that recompiling cause I don’t want to start over and again ty for the help
